# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libbook',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libbook',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='context',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='note',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='libbook',
            name='barid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='libbook',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='note',
            field=models.TextField(default='', null=True),
        ),
    ]
