# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170430_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowright',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
