# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_auto_20170430_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowtime', models.DateTimeField(auto_now_add=True)),
                ('returntime', models.DateTimeField(blank=True, null=True)),
                ('borrowtype', models.CharField(default='b', max_length=6)),
                ('returntype', models.CharField(default='n', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookoperation',
            name='libbook',
        ),
        migrations.RemoveField(
            model_name='bookoperation',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='bookoperation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='borrowright',
            name='group',
        ),
        migrations.RemoveField(
            model_name='libbook',
            name='borrowuser',
        ),
        migrations.DeleteModel(
            name='BookOperation',
        ),
        migrations.DeleteModel(
            name='BorrowRight',
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='libbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.LibBook'),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
