# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20170509_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='clc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubhouse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libbook',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
