# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('booknum', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('allowborrow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBorrowRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowright', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BorrowRight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
